all:
  hosts:
    localhost:
  children:
    elasticsearch_masters:
      children:
        elasticsearch_primary_master:
        elasticsearch_master:
    elasticsearch_primary_master:
      hosts:
        elastic01:
          ansible_user: philranzato
          ansible_private_key_file: ~/.ssh/id_rsa_phil
          ansible_host: 35.228.153.8
    elasticsearch_master:
      hosts:
        elastic01:
          ansible_user: philranzato
          ansible_private_key_file: ~/.ssh/id_rsa_phil
          ansible_host: 35.228.153.8
        elastic02:
          ansible_user: philranzato
          ansible_private_key_file: ~/.ssh/id_rsa_phil
          ansible_host: 35.228.248.253
        elastic03:
          ansible_user: philranzato
          ansible_private_key_file: ~/.ssh/id_rsa_phil
          ansible_host: 35.228.28.179
    logstash:
      hosts:
        logstash01:
          ansible_user: philranzato
          ansible_private_key_file: ~/.ssh/id_rsa_phil
          ansible_host: 35.228.64.44
    kibana:
      hosts:
        kibana01:
          ansible_user: philranzato
          ansible_private_key_file: ~/.ssh/id_rsa_phil
          ansible_host: 35.228.166.220
        