all:
  hosts:
    localhost:
  children:
    elasticsearch_masters:
      children:
        elasticsearch_primary_master:
        elasticsearch_master:
    elasticsearch_primary_master:
      hosts:
        c7els01.pr.ch:
    elasticsearch_master:
      hosts:
        c7els01.pr.ch:
        c7els02.pr.ch:
        c7els03.pr.ch:
    logstash:
      hosts:
        c7lgs01.pr.ch:
    kibana:
      hosts:
        c7kbn01.pr.ch:
        