---
- name: "Generate internal CA"
  hosts: elasticsearch_primary_master
  become: true
  roles:
  - { role: philranzato.certificate-openssl }
  vars_files:
  - vars/01-ca.yml

- name: "Install Elasticsearch"
  hosts: elasticsearch_masters
  become: true
  roles:
  - { role: philranzato.elasticsearch-install }

- name: "Install Logstash"
  hosts: logstash
  roles:
  - { role: philranzato.logstash-install }

- name: "Install Kibana"
  hosts: kibana
  become: true
  roles:
  - { role: philranzato.kibana-install }

- name: "Fetch CA"
  hosts: elasticsearch_primary_master
  roles:
  - { role: philranzato.elk-utils }
  vars_files:
  - vars/03-fetch-ca.yml

- name: "Copy CA to all hosts"
  hosts: all:!localhost
  roles:
  - { role: philranzato.elk-utils }
  vars_files:
  - vars/03-copy-ca.yml
  serial: 1

- name: "Generate Elasticsearch Certificates"
  hosts: elasticsearch_primary_master
  become: true
  roles:
  - { role: philranzato.elasticsearch-certificate }
  vars_files:
  - vars/03-certificates-elasticsearch.yml

- name: "Generate Logstash Certificates"
  hosts: elasticsearch_primary_master
  become: true
  roles:
  - { role: philranzato.elasticsearch-certificate }
  vars_files:
  - vars/03-certificates-logstash.yml

- name: "Fetch certificates"
  hosts: elasticsearch_primary_master
  roles:
  - { role: philranzato.elk-utils }
  vars_files:
  - vars/04-fetch.yml

- name: "Copy certificates and keys to all hosts"
  hosts: all:!localhost
  roles:
  - { role: philranzato.elk-utils }
  vars_files:
  - vars/04-copy.yml
  serial: 1

- name: "Configure Elasticsearch"
  hosts: elasticsearch_masters
  roles:
  - { role: philranzato.elasticsearch-configuration }
  vars_files:
  - vars/05-es-config.yml

- name: "Configure Logstash"
  hosts: logstash
  roles:
  - { role: philranzato.logstash-configuration }
  vars_files:
  - vars/06-lgs-config.yml

- name: "Create Certificate for Kibana"
  hosts: kibana
  roles:
  - { role: philranzato.certificate-openssl }
  vars_files:
  - vars/07-kbn-certificate.yml

- name: "Configure Kibana"
  hosts: kibana
  roles:
  - { role: philranzato.kibana-configuration }
  vars_files:
  - vars/07-kbn-config.yml

- name: "Install and Configure Nginx"
  hosts: kibana
  roles:
  - { role: philranzato.nginx }
  vars_files:
  - vars/08-nginx.yml

- name: "Create Certificate for Filebeat client authentication"
  hosts: kibana
  roles:
  - { role: philranzato.certificate-openssl }
  vars_files:
  - vars/09-filebeat-client-certificate.yml

- name: "Create Certificate for Logstash server authentication"
  hosts: logstash
  roles:
  - { role: philranzato.certificate-openssl }
  vars_files:
  - vars/09-logstash-server-certificate.yml

- name: "Convert Logstash key into pkcs8 format"
  hosts: logstash
  roles:
  - { role: philranzato.elk-utils }
  vars_files:
  - vars/09-logstash-server-certificate.yml

- name: "Install and Configure Filebeat"
  hosts: kibana
  roles:
  - { role: philranzato.filebeat }
  vars_files:
  - vars/09-filebeat.yml

- name: "Configure Logstash to accept filebeat input"
  hosts: logstash
  roles:
  - { role: philranzato.logstash-configuration }
  vars_files:
  - vars/09-logstash-filebeat-input.yml
