---
- name: "Generate internal CA"
  hosts: elasticsearch_primary_master
  become: true
  roles:
  - { role: pllr.certificate-openssl }
  vars_files:
  - vars/ca.yml

- name: "Install Elasticsearch"
  hosts: elasticsearch_masters
  become: true
  roles:
  - { role: pllr.elasticsearch-install }

- name: "Install Logstash"
  hosts: logstash
  become: true
  roles:
  - { role: pllr.logstash-install }

- name: "Install Kibana"
  hosts: kibana
  become: true
  roles:
  - { role: pllr.kibana-install }

- name: "Generate Elasticsearch Certificates"
  hosts: elasticsearch_primary_master
  become: true
  roles:
  - { role: pllr.elasticsearch-certificate }
  vars_files:
  - vars/03-certificates-elasticsearch.yml

- name: "Generate Logstash Certificates"
  hosts: elasticsearch_primary_master
  become: true
  roles:
  - { role: pllr.elasticsearch-certificate }
  vars_files:
  - vars/03-certificates-logstash.yml

- name: "Fetch certificates"
  hosts: elasticsearch_primary_master
  roles:
  - { role: pllr.elk-utils }
  vars_files:
  - vars/04-fetch.yml

- name: "Copy certificates and keys to all hosts"
  hosts: all:!localhost
  roles:
  - { role: pllr.elk-utils }
  vars_files:
  - vars/04-copy.yml
  serial: 1
