---
- name: "Generate internal CA"
  hosts: elasticsearch_primary_master
  become: true
  roles:
  - { role: philranzato.certificate-openssl }
  vars_files:
  - vars/01-ca.yml

- name: "Install Elasticsearch"
  hosts: elasticsearch_masters
  become: true
  roles:
  - { role: philranzato.elasticsearch-install }

- name: "Install Logstash"
  hosts: logstash
  roles:
  - { role: philranzato.logstash-install }

- name: "Install Kibana"
  hosts: kibana
  become: true
  roles:
  - { role: philranzato.kibana-install }

- name: "Generate Elasticsearch Certificates"
  hosts: elasticsearch_primary_master
  become: true
  roles:
  - { role: philranzato.elasticsearch-certificate }
  vars_files:
  - vars/03-certificates-elasticsearch.yml

- name: "Generate Logstash Certificates"
  hosts: elasticsearch_primary_master
  become: true
  roles:
  - { role: philranzato.elasticsearch-certificate }
  vars_files:
  - vars/03-certificates-logstash.yml

- name: "Fetch certificates"
  hosts: elasticsearch_primary_master
  roles:
  - { role: philranzato.elk-utils }
  vars_files:
  - vars/04-fetch.yml

- name: "Copy certificates and keys to all hosts"
  hosts: all:!localhost
  roles:
  - { role: philranzato.elk-utils }
  vars_files:
  - vars/04-copy.yml
  serial: 1

- name: "Configure Elasticsearch"
  hosts: elasticsearch_masters
  roles:
  - { role: philranzato.elasticsearch-configuration }
  vars_files:
  - vars/05-es-config.yml

- name: "Configure Logstash"
  hosts: logstash
  roles:
  - { role: philranzato.logstash-configuration }
  vars_files:
  - vars/06-lgs-config.yml
