---
- name: "Gather facts from all hosts"
  hosts: all:!localhost
  tasks:
  - name: "Print IP"
    debug:
      msg: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"

- name: "Create Certificate for Kibana"
  hosts: kibana
  roles:
  - { role: philranzato.certificate-openssl }
  vars_files:
  - vars/07-kbn-certificate.yml

- name: "Configure Kibana"
  hosts: kibana
  roles:
  - { role: philranzato.kibana-configuration }
  vars_files:
  - vars/07-kbn-config.yml
