---
- name: "Install Elasticsearch"
  hosts: elasticsearch_master
  become: true
  roles:
  - { role: philranzato.elasticsearch-install }

- name: "Install Logstash"
  hosts: logstash
  become: true
  roles:
  - { role: philranzato.logstash-install }

- name: "Install Kibana"
  hosts: kibana
  become: true
  roles:
  - { role: philranzato.kibana-install }
