---
- name: "Fetch certificates"
  hosts: elasticsearch_primary_master
  roles:
  - { role: philranzato.elk-utils }
  vars_files:
  - vars/04-fetch.yml

- name: "Copy certificates and keys to all hosts"
  hosts: all:!localhost
  roles:
  - { role: philranzato.elk-utils }
  vars_files:
  - vars/04-copy.yml
  serial: 1
