---
- name: "Gather facts from all hosts"
  hosts: all:!localhost
  tasks:
  - name: "Print IP"
    debug:
      msg: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"

- name: "Configure Logstash"
  hosts: logstash
  roles:
  - { role: philranzato.logstash-configuration }
  vars_files:
  - vars/06-lgs-config.yml
