---
- name: "Install Elasticsearch"
  hosts: elasticsearch_master
  become: true
  roles:
  - { role: plrr.elasticsearch-install }

- name: "Install Logstash"
  hosts: logstash
  become: true
  roles:
  - { role: plrr.logstash-install }

- name: "Install Kibana"
  hosts: kibana
  become: true
  roles:
  - { role: plrr.kibana-install }
